name: go vet compile

on:
  pull_request:
  workflow_dispatch:

jobs:
  vet:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.0'

      - name: Run go vet (just for compile)
        env:
          GOROOT: ${{ github.workspace }}
        working-directory: src/cmd
        run: |
          go vet ./compile/...


