name: riscv64-rva23

on:
  pull_request:
  workflow_dispatch: 

jobs:
  riscv64-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Enable QEMU (riscv64)
        uses: docker/setup-qemu-action@v3
        with:
          platforms: riscv64

      - name: Run tests in riscv64 container (QEMU)
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: riscv64
          distro: ubuntu22.04
          install: |
            apt-get update
            apt-get install -y curl xz-utils build-essential ca-certificates git
          run: |
            set -eux
            # 1) 在 riscv64 环境中安装 bootstrap Go
            BOOT=/usr/local/go-bootstrap
            curl -fsSL https://go.dev/dl/go1.25.0.linux-riscv64.tar.gz -o /tmp/go.tar.gz
            tar -C /usr/local -xzf /tmp/go.tar.gz
            mv /usr/local/go "$BOOT"
            export GOROOT_BOOTSTRAP="$BOOT"
            export PATH="$PATH:/usr/local/go-bootstrap/bin"

            # 2) 进入 Go 源码树并构建+测试（QEMU 下的 riscv64）
            # cd "$GITHUB_WORKSPACE/src"
            # ./all.bash

            cd "$GITHUB_WORKSPACE/rv23test/zicond"
            # file ./zicond.rv64
            ./zicond.rv64

            cd "$GITHUB_WORKSPACE/src"
            ./make.bash

            export GOROOT="$GITHUB_WORKSPACE"
            cd "$GITHUB_WORKSPACE/rv23test/zicond"
            "$GOROOT/bin/go" build -o zicond2.rv64 zicond.go

            # file ./zicond2.rv64
            ./zicond2.rv64
            
            export GORISCV64=rva23u64
            "$GOROOT/bin/go" build -o zicond3.rv64 zicond.go
            # file ./zicond3.rv64
            ./zicond3.rv64

